language: node_js
node_js:
  - node
  - lts/*
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE gbl_development;'
install:
  - npm install
script:
  - npm run lint
  - npm run db:init
  - npm test
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
