language: node_js
node_js:
  - node
  - lts/*
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE gbl_development;'
install:
  - npm install
script:
  - npm run lint
  - npm run db:init
  - npm test

