language: node_js
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE gbl_development;'
install:
  -  npm install
script:
  -  npm run lint
  -  npm test

